export interface FormatPreset {
  platform: string;
  label: string;
  aspectRatio: '9:16' | '1:1' | '4:5' | '16:9';
  width: number;
  height: number;
  maxDuration: number;
  recommendedDuration: number | null;
  codec: string;
  videoBitrate: string;
  audioBitrate: string;
  fps: number;
  category: 'organic' | 'ad';
}

export const FORMAT_PRESETS: Record<string, FormatPreset> = {
  youtube_shorts: {
    platform: 'YouTube Shorts',
    label: 'YouTube Shorts',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    maxDuration: 60,
    recommendedDuration: null,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'organic',
  },
  instagram_reels: {
    platform: 'Instagram',
    label: 'Instagram Reels',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    maxDuration: 90,
    recommendedDuration: null,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'organic',
  },
  tiktok: {
    platform: 'TikTok',
    label: 'TikTok',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    maxDuration: 180,
    recommendedDuration: null,
    codec: 'libx264',
    videoBitrate: '6M',
    audioBitrate: '128k',
    fps: 30,
    category: 'organic',
  },
  facebook_reels: {
    platform: 'Facebook',
    label: 'Facebook Reels',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    maxDuration: 90,
    recommendedDuration: null,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'organic',
  },
  facebook_feed: {
    platform: 'Facebook',
    label: 'Facebook Feed (Square)',
    aspectRatio: '1:1',
    width: 1080,
    height: 1080,
    maxDuration: 240,
    recommendedDuration: null,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'organic',
  },
  fb_ig_feed_ad: {
    platform: 'Facebook/Instagram',
    label: 'FB/IG Feed Ad (Square)',
    aspectRatio: '1:1',
    width: 1080,
    height: 1080,
    maxDuration: 240,
    recommendedDuration: 30,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'ad',
  },
  fb_ig_feed_ad_portrait: {
    platform: 'Facebook/Instagram',
    label: 'FB/IG Feed Ad (Portrait)',
    aspectRatio: '4:5',
    width: 1080,
    height: 1350,
    maxDuration: 240,
    recommendedDuration: 30,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'ad',
  },
  fb_ig_story_ad: {
    platform: 'Facebook/Instagram',
    label: 'FB/IG Story/Reel Ad',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    maxDuration: 120,
    recommendedDuration: 15,
    codec: 'libx264',
    videoBitrate: '8M',
    audioBitrate: '128k',
    fps: 30,
    category: 'ad',
  },
  youtube_ad: {
    platform: 'YouTube',
    label: 'YouTube In-Stream Ad',
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    maxDuration: 180,
    recommendedDuration: 30,
    codec: 'libx264',
    videoBitrate: '10M',
    audioBitrate: '128k',
    fps: 30,
    category: 'ad',
  },
  tiktok_ad: {
    platform: 'TikTok',
    label: 'TikTok In-Feed Ad',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    maxDuration: 60,
    recommendedDuration: 15,
    codec: 'libx264',
    videoBitrate: '6M',
    audioBitrate: '128k',
    fps: 30,
    category: 'ad',
  },
};
